id: P919205C3
initial_creation_type: input
source_metadata:
  title: Ṛgvedasaṃhitā, Padapāṭha
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Veda -- Saṃhitā
  data entry: members of the Sansknet Project
  contribution to GRETIL: members of the Sansknet Project
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:47:16.214247'
last_modified_at: '2022-03-09T14:47:16.214267'
